# Generated by Django 6.0.3 on 2026-03-16 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultation",
            options={"ordering": ("-date", "-time")},
        ),
        migrations.AddField(
            model_name="consultation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="consultation",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="consultation",
            name="goals",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="is_free_intro_call",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="consultation",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("ielts_plan", "IELTS Plan"),
                    ("sat_plan", "SAT Plan"),
                    ("admission", "Admission Support"),
                    ("essay", "Essay Review"),
                    ("career", "Career Mapping"),
                ],
                default="ielts_plan",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
