# Generated by Django 6.0.3 on 2026-03-16 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0004_favoritementor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentoravailability",
            options={"ordering": ("date", "time")},
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="headline",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="languages",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="offers_admission_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="primary_track",
            field=models.CharField(
                choices=[
                    ("ielts", "IELTS"),
                    ("sat", "SAT"),
                    ("admission", "Admission"),
                    ("strategy", "Study Strategy"),
                ],
                default="ielts",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="students_helped",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="success_story_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="university_background",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="mentoravailability",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mentors.mentorprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoritementor",
            unique_together={("user", "mentor")},
        ),
        migrations.AlterUniqueTogether(
            name="mentoravailability",
            unique_together={("mentor", "date", "time")},
        ),
    ]
